version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "jakarta.platform:jakarta.jakartaee-api"
      - dependency-name: "org.eclipse.microprofile:microprofile"
